# Generated by Django 5.0.4 on 2024-06-25 10:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AverageMonthScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=9)),
                ('average_sentiment', models.FloatField()),
                ('average_joy_score', models.FloatField()),
                ('average_sadness_score', models.FloatField()),
                ('average_anger_score', models.FloatField()),
                ('average_fear_score', models.FloatField()),
                ('average_disgust_score', models.FloatField()),
            ],
            options={
                'verbose_name': 'average month score',
                'verbose_name_plural': 'average months scores',
            },
        ),
        migrations.CreateModel(
            name='AverageWeekScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('average_sentiment', models.FloatField()),
                ('average_joy_score', models.FloatField()),
                ('average_sadness_score', models.FloatField()),
                ('average_anger_score', models.FloatField()),
                ('average_fear_score', models.FloatField()),
                ('average_disgust_score', models.FloatField()),
            ],
            options={
                'verbose_name': 'average week score',
                'verbose_name_plural': 'average weeks scores',
            },
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'user input',
                'verbose_name_plural': 'user inputs',
            },
        ),
        migrations.CreateModel(
            name='SentimentEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField()),
                ('sentiment_label', models.CharField(max_length=20)),
                ('joy_score', models.FloatField()),
                ('sadness_score', models.FloatField()),
                ('anger_score', models.FloatField()),
                ('fear_score', models.FloatField()),
                ('disgust_score', models.FloatField()),
                ('user_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userinput')),
            ],
            options={
                'verbose_name': 'sentiment emotion',
                'verbose_name_plural': 'sentiments emotions',
            },
        ),
    ]
