# Generated by Django 5.0.4 on 2024-04-15 08:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='AverageWeekScores',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('average_sentiment', models.FloatField()),
                ('average_joy_score', models.FloatField()),
                ('average_sadness_score', models.FloatField()),
                ('average_anger_score', models.FloatField()),
                ('average_fear_score', models.FloatField()),
                ('average_disgust_score', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
            options={
                'verbose_name': 'average week score',
                'verbose_name_plural': 'average weeks scores',
            },
        ),
        migrations.CreateModel(
            name='AverageMonthScores',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=9)),
                ('average_sentiment', models.FloatField()),
                ('average_joy_score', models.FloatField()),
                ('average_sadness_score', models.FloatField()),
                ('average_anger_score', models.FloatField()),
                ('average_fear_score', models.FloatField()),
                ('average_disgust_score', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
            options={
                'verbose_name': 'average month score',
                'verbose_name_plural': 'average months scores',
            },
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
            options={
                'verbose_name': 'user input',
                'verbose_name_plural': 'user inputs',
            },
        ),
        migrations.CreateModel(
            name='SentimentEmotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sentiment_score', models.FloatField()),
                ('joy_score', models.FloatField()),
                ('sadness_score', models.FloatField()),
                ('anger_score', models.FloatField()),
                ('fear_score', models.FloatField()),
                ('disgust_score', models.FloatField()),
                ('user_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userinput')),
            ],
            options={
                'verbose_name': 'sentiment emotion',
                'verbose_name_plural': 'sentiments emotions',
            },
        ),
    ]
