# Generated by Django 5.0.4 on 2024-07-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AverageMonthScores',
        ),
        migrations.DeleteModel(
            name='AverageWeekScores',
        ),
    ]
