# Generated by Django 5.0.4 on 2024-06-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_id_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averageweekscores',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinput',
            name='user',
        ),
        migrations.RemoveField(
            model_name='averagemonthscores',
            name='user',
        ),
        migrations.AlterField(
            model_name='averagemonthscores',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='averageweekscores',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sentimentemotion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
