# Generated by Django 5.0.4 on 2024-06-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_averageweekscores_user_remove_userinput_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentemotion',
            name='sentiment_label',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
