# Generated by Django 5.0.4 on 2024-06-25 07:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_sentimentemotion_sentiment_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentimentemotion',
            name='disgust_score',
        ),
        migrations.AlterField(
            model_name='userinput',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
